import type { IncomingMessage, ServerResponse } from "http";
import { randomUUID } from "crypto";
import type { JsonRpcRequest, JsonRpcResponse } from "../protocol/types.js";
import { MCP_BASELINE_VERSION, ErrorCodes, isJsonRpcRequestShape } from "../protocol/types.js";
import { type Codec, getCodec, getCodecForContentType } from "../encoding/codec.js";
import {
  buildPRMDocument,
  buildWWWAuthenticate,
  validateToken,
  type JwtHeader,
  type JwtPayload,
} from "../auth/oauth21.js";

/** RFC 9728 well-known path for Protected Resource Metadata. */
const PRM_PATH = "/.well-known/oauth-protected-resource";

export type HttpMessageHandler = (
  msg: JsonRpcRequest,
  req: IncomingMessage,
  /**
   * Session identity (MCP Streamable HTTP `Mcp-Session-Id`). Generated by the
   * transport on `initialize`, echoed back by the client on every subsequent
   * request. Lets a single handler instance keep per-client negotiation state.
   */
  sessionId?: string
) => Promise<JsonRpcResponse | null>;

export interface HttpHandlerOptions {
  /** Require a Bearer token on every POST. Default: true. Set false for local/dev use. */
  authRequired?: boolean;
  /** Max request body size in bytes. Oversized requests get 413. Default: 4 MiB. */
  maxBodyBytes?: number;
  /** Per-request handler deadline. Slower handlers get 504. Default: 30s. */
  requestTimeoutMs?: number;
  /**
   * Fixed-window per-IP rate limit. Over-limit requests get 429 + Retry-After.
   * Checked before auth so token validation can't be used as an amplifier.
   * In-memory — for multi-instance deployments put a shared limiter (reverse
   * proxy, Redis) in front instead.
   */
  rateLimit?: { limit: number; windowMs: number };
  /**
   * Trust the first hop in `X-Forwarded-For` as the client IP for rate
   * limiting. Enable ONLY behind a reverse proxy that strips/sets the header —
   * otherwise clients can spoof their way past the limiter. Default: false
   * (socket address; behind a proxy all clients then share one bucket).
   */
  trustProxy?: boolean;
  /**
   * Origins allowed to reach this server from a browser (DNS-rebinding
   * protection — the MCP Streamable HTTP spec requires Origin validation).
   * Requests carrying an `Origin` header not in this list get 403. Requests
   * without an `Origin` header (every non-browser client) are unaffected.
   * Default: empty — all browser-originated requests are rejected until the
   * operator explicitly allows their origins.
   */
  allowedOrigins?: string[];
  /**
   * Validate the bearer token (the raw value after "Bearer "). Return true to
   * accept. When omitted, auth is *presence-only* — any non-empty Bearer value
   * passes. Presence-only is dev-grade; wire a real validator (see
   * `validateToken` in ../auth/oauth21) for production.
   */
  validateToken?: (token: string, req: IncomingMessage) => boolean | Promise<boolean>;
  /**
   * Full OAuth 2.1 resource-server mode. When set, the transport serves the
   * RFC 9728 PRM document at `/.well-known/oauth-protected-resource`, validates
   * bearer tokens for audience (RFC 8707) + expiry + signature, and emits
   * spec-compliant `WWW-Authenticate` challenges with error reasons.
   *
   * Takes precedence over `validateToken` (the presence-only dev hook).
   */
  oauth?: {
    /** This server's canonical URL — must match the token `aud` claim (RFC 8707). */
    resourceUrl: string;
    /** Authorization servers advertised in the PRM document. */
    authorizationServers: string[];
    /** Verify the JWT signature. Without it, audience + expiry are still enforced. */
    verifySignature?: (token: string, header: JwtHeader, payload: JwtPayload) => Promise<boolean>;
    /** RFC 7662 introspection endpoint, used when `verifySignature` is absent. */
    introspectionEndpoint?: string;
    clientCredentials?: { id: string; secret: string };
    /** Optional PRM hints. */
    signingAlgs?: string[];
    documentationUrl?: string;
  };
}

/**
 * Streamable HTTP transport (MCP 2025-11-25 spec).
 * Single endpoint, optional SSE on GET.
 * Validates MCP-Protocol-Version header — required from 2025-06-18 onward.
 *
 * The MCP-Protocol-Version header carries the *baseline MCP* version
 * (`MCP_BASELINE_VERSION`) for ecosystem interop; Delta-MCP extensions are
 * advertised separately in the initialize result's `capabilities`.
 */
export function createHttpHandler(handler: HttpMessageHandler, opts: HttpHandlerOptions = {}) {
  const authRequired = opts.authRequired ?? true;
  const maxBodyBytes = opts.maxBodyBytes ?? DEFAULT_MAX_BODY_BYTES;
  const requestTimeoutMs = opts.requestTimeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS;
  const limiter = opts.rateLimit ? createRateLimiter(opts.rateLimit) : null;

  // Fail loudly on a forgeable-token configuration. Without one of these two,
  // validateToken only checks structure + audience + expiry — anyone can mint
  // an unsigned JWT with the right `aud` claim and walk in.
  if (opts.oauth && !opts.oauth.verifySignature && !opts.oauth.introspectionEndpoint) {
    throw new Error(
      "oauth mode requires `verifySignature` or `introspectionEndpoint` — " +
        "without either, bearer tokens are not cryptographically verified and can be forged. " +
        "For an unauthenticated dev server, omit `oauth` and set `authRequired: false`."
    );
  }

  // Presence-only bearer check accepts ANY non-empty token. Fine for local
  // development; say so once at startup rather than silently in production.
  if (authRequired && !opts.oauth && !opts.validateToken) {
    process.emitWarning(
      "delta-mcp HTTP auth is presence-only (any non-empty Bearer token passes). " +
        "Wire `oauth` or `validateToken` before exposing this server.",
      { code: "DELTA_MCP_PRESENCE_ONLY_AUTH" }
    );
  }

  const handleRequest = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    res.setHeader("MCP-Protocol-Version", MCP_BASELINE_VERSION);
    const clientVersion = req.headers["mcp-protocol-version"] as string | undefined;

    // Rate limit first — cheapest check, shields auth + body parsing.
    if (limiter) {
      const verdict = limiter(clientIp(req, opts.trustProxy ?? false));
      if (!verdict.allowed) {
        res.writeHead(429, { "Retry-After": String(verdict.retryAfterSeconds) });
        res.end();
        return;
      }
    }

    // DNS-rebinding protection (spec MUST): a browser page can reach
    // localhost-bound servers via a rebound hostname, but it cannot forge the
    // Origin header. Reject any browser-originated request whose Origin the
    // operator hasn't explicitly allowed. Non-browser clients send no Origin.
    const origin = firstHeader(req.headers.origin);
    if (origin !== undefined) {
      if (!(opts.allowedOrigins ?? []).includes(origin)) {
        res.writeHead(403);
        res.end();
        return;
      }
      // Allowed browser origin — without CORS headers the browser would block
      // the response it just allowed us to receive.
      res.setHeader("Access-Control-Allow-Origin", origin);
      res.setHeader("Vary", "Origin");
      res.setHeader(
        "Access-Control-Expose-Headers",
        "Mcp-Session-Id, MCP-Protocol-Version, WWW-Authenticate"
      );
      if (req.method === "OPTIONS") {
        res.writeHead(204, {
          "Access-Control-Allow-Methods": "POST, OPTIONS",
          "Access-Control-Allow-Headers":
            "Content-Type, Accept, Authorization, MCP-Protocol-Version, Mcp-Session-Id",
          "Access-Control-Max-Age": "86400",
        });
        res.end();
        return;
      }
    }

    // RFC 9728 Protected Resource Metadata — unauthenticated discovery endpoint.
    // Served only in full OAuth mode; lets a client follow the 401 challenge to
    // find its authorization server.
    if (opts.oauth && req.method === "GET" && reqPath(req) === PRM_PATH) {
      const prm = buildPRMDocument(opts.oauth.resourceUrl, opts.oauth.authorizationServers, {
        signingAlgs: opts.oauth.signingAlgs,
        documentationUrl: opts.oauth.documentationUrl,
      });
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(prm));
      return;
    }

    // Server-initiated SSE streams are not implemented. The Streamable HTTP
    // spec allows a server to decline by answering 405 — honest, unlike an
    // open stream that never emits an event and leaves the client hanging.
    if (req.method !== "POST") {
      res.writeHead(405, { Allow: "POST" });
      res.end();
      return;
    }

    // OAuth 2.1 resource-server role: validate bearer token.
    if (opts.oauth) {
      // Full mode: RFC 8707 audience + expiry + signature, spec WWW-Authenticate.
      const prmUrl = `${opts.oauth.resourceUrl}${PRM_PATH}`;
      const auth = req.headers.authorization;
      const token = auth?.startsWith("Bearer ") ? auth.slice(7).trim() : "";
      if (token.length === 0) {
        res.writeHead(401, { "WWW-Authenticate": buildWWWAuthenticate(prmUrl) });
        res.end();
        return;
      }
      const validation = await validateToken(token, opts.oauth.resourceUrl, {
        verifySignature: opts.oauth.verifySignature,
        introspectionEndpoint: opts.oauth.introspectionEndpoint,
        clientCredentials: opts.oauth.clientCredentials,
      });
      if (!validation.valid) {
        res.writeHead(401, {
          "WWW-Authenticate": buildWWWAuthenticate(prmUrl, {
            error: "invalid_token",
            errorDescription: validation.error ?? "Token validation failed",
          }),
        });
        res.end();
        return;
      }
    } else if (authRequired) {
      // Presence-only dev mode (or custom `validateToken` hook).
      const auth = req.headers.authorization;
      const token = auth?.startsWith("Bearer ") ? auth.slice(7).trim() : "";
      const ok = token.length > 0 && (opts.validateToken ? await opts.validateToken(token, req) : true);
      if (!ok) {
        res.writeHead(401, {
          "WWW-Authenticate": `Bearer realm="delta-mcp", resource_metadata="${PRM_PATH}"`,
        });
        res.end();
        return;
      }
    }

    const reqCodec = getCodecForContentType(req.headers["content-type"]);
    let body: Buffer;
    try {
      body = await readBody(req, maxBodyBytes);
    } catch (err) {
      if (err instanceof BodyTooLarge) {
        // Close the connection once the 413 is flushed — never drain the rest
        // of an attacker-sized payload.
        res.writeHead(413, { Connection: "close" });
        res.end(() => req.destroy());
        return;
      }
      throw err;
    }
    let msg: JsonRpcRequest;
    try {
      msg = reqCodec.decode(body) as JsonRpcRequest;
    } catch {
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: ErrorCodes.PARSE_ERROR, message: "Parse error" } }));
      return;
    }

    // Valid JSON that is not a JSON-RPC request ("42", arrays, strings) must
    // get INVALID_REQUEST — not slip through as a "notification" and 202.
    if (!isJsonRpcRequestShape(msg)) {
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: ErrorCodes.INVALID_REQUEST, message: "Invalid Request" } }));
      return;
    }

    // Version header is mandatory on every request *except* initialize — the
    // client doesn't know the negotiated version until initialize returns.
    if (msg.method !== "initialize" && !clientVersion) {
      return sendMissingVersion(res);
    }

    // Session identity (MCP Streamable HTTP). One handler instance serves many
    // clients, so negotiation state must be keyed per session: a fresh id is
    // minted on initialize and returned via Mcp-Session-Id; the client echoes
    // it on every later request.
    let sessionId = firstHeader(req.headers["mcp-session-id"]);
    if (msg.method === "initialize") {
      sessionId = randomUUID();
      res.setHeader("Mcp-Session-Id", sessionId);
    }

    // Deadline on the handler: a hung tool must not pin the connection open.
    let response: JsonRpcResponse | null;
    try {
      response = await withTimeout(handler(msg, req, sessionId), requestTimeoutMs);
    } catch (err) {
      if (err instanceof HandlerTimeout) {
        res.writeHead(504);
        res.end();
        return;
      }
      throw err;
    }
    if (!response) {
      // Notification — MCP Streamable HTTP: 202 Accepted, no body.
      res.writeHead(202);
      res.end();
      return;
    }
    const resCodec = pickResponseCodec(req.headers.accept, reqCodec);
    res.writeHead(200, { "Content-Type": resCodec.contentType });
    res.end(resCodec.encode(response));
  };

  // Containment: any error that escapes the request pipeline (a throwing
  // message handler, a codec failure) must become a 500 on this connection —
  // never an unhandled rejection that takes the whole process down.
  return async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    try {
      await handleRequest(req, res);
    } catch {
      if (!res.headersSent) res.writeHead(500);
      res.end();
    }
  };
}

/** Node lowercases header names; multi-valued headers arrive as arrays. */
function firstHeader(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

/**
 * Client IP for rate limiting. With trustProxy, the first (client-most) hop in
 * X-Forwarded-For; otherwise the socket address.
 */
function clientIp(req: IncomingMessage, trustProxy: boolean): string {
  if (trustProxy) {
    const xff = firstHeader(req.headers["x-forwarded-for"]);
    const first = xff?.split(",")[0]?.trim();
    if (first) return first;
  }
  return req.socket.remoteAddress ?? "unknown";
}

/** Extract the path component of a request URL, ignoring any query string. */
function reqPath(req: IncomingMessage): string {
  const raw = req.url ?? "/";
  const q = raw.indexOf("?");
  return q === -1 ? raw : raw.slice(0, q);
}

function sendMissingVersion(res: ServerResponse): void {
  res.writeHead(400, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ error: "Missing MCP-Protocol-Version header" }));
}

/** Choose response codec from the client's Accept header, else echo the request codec. */
function pickResponseCodec(accept: string | undefined, fallback: Codec): Codec {
  if (accept) {
    if (accept.includes("application/cbor")) return getCodec("cbor");
    if (accept.includes("variant=compact")) return getCodec("compact-json");
    if (accept.includes("application/json")) return getCodec("json");
  }
  return fallback;
}

const DEFAULT_MAX_BODY_BYTES = 4 * 1024 * 1024; // 4 MiB
const DEFAULT_REQUEST_TIMEOUT_MS = 30_000;

class BodyTooLarge extends Error {}
class HandlerTimeout extends Error {}

/** Read the request body, aborting the stream as soon as the limit is crossed. */
function readBody(req: IncomingMessage, maxBytes: number): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let received = 0;
    req.on("data", (c: Buffer) => {
      received += c.length;
      if (received > maxBytes) {
        // Stop reading without killing the socket yet — the caller still needs
        // to flush a 413 before the connection is torn down.
        req.pause();
        reject(new BodyTooLarge());
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new HandlerTimeout()), ms);
    promise.then(
      (v) => { clearTimeout(timer); resolve(v); },
      (e) => { clearTimeout(timer); reject(e); }
    );
  });
}

type RateVerdict = { allowed: true } | { allowed: false; retryAfterSeconds: number };

/**
 * Fixed-window per-IP counter. A full sweep runs at most once per window so
 * the map cannot grow unbounded under a rotating-IP flood.
 */
function createRateLimiter(cfg: { limit: number; windowMs: number }): (ip: string) => RateVerdict {
  const windows = new Map<string, { count: number; resetAt: number }>();
  let lastSweep = Date.now();

  return (ip: string): RateVerdict => {
    const now = Date.now();

    if (now - lastSweep > cfg.windowMs) {
      for (const [key, w] of windows) if (now >= w.resetAt) windows.delete(key);
      lastSweep = now;
    }

    const win = windows.get(ip);
    if (!win || now >= win.resetAt) {
      windows.set(ip, { count: 1, resetAt: now + cfg.windowMs });
      return { allowed: true };
    }
    if (win.count >= cfg.limit) {
      return { allowed: false, retryAfterSeconds: Math.max(1, Math.ceil((win.resetAt - now) / 1000)) };
    }
    win.count += 1;
    return { allowed: true };
  };
}
